spring.application.name=aula07


server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/curso_tecnico
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
 spring.jpa.show-sql=true
 spring.jpa.properties.hibernate.format_sql=true
 spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 spring.jackson.deserialization.fail-on-unknown-properties=true
 spring.web.error.include-stacktrace=never