# declarando a porta do servidor
server.port=8080

# Conexão com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/aula03_API
# spring.datasource.url=jdbc:h2:file:./h2/banco;DB_CLOSE_DELAY=-1

# Dados do usuários #

## POSTGRES
spring.datasource.username=postgres
spring.datasource.password=1234

## H2
# spring.datasource.username=sa
# spring.datasource.password=1234

# Cmd para mostrar no console de Depuração
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

#DDL - como hibernate trata a estrutura do Banco
#  spring.jpa.hibernate.ddl-auto=update
 spring.jpa.generate-ddl=true

#SQL no console
 spring.jpa.show-sql=true
 spring.jpa.properties.hibernate.format_sql=true

#Definindo o Dialeto
 spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Defini que todos os erros no arquivo application.properties, teremos como retorno o erro 400 bad request.
spring.jackson.deserialization.fail-on-unknown-properties=true

#Oculta o campo trace
spring.web.error.include-stacktrace=never

# nome da aplicação
spring.application.name=alula03
